CC= gnatmake

all: test_matrice_sure test_matrice_sure1 test_matrice_sure2 test_matrice_sure3

test_matrice_sure:test_matrice_sure.adb
	$(CC) test_matrice_sure.adb

test_matrice_sure1:test_matrice_sure1.adb
	$(CC) test_matrice_sure1.adb

test_matrice_sure2:test_matrice_sure2.adb
	$(CC) test_matrice_sure2.adb

test_matrice_sure3:test_matrice_sure3.adb
	$(CC) test_matrice_sure3.adb

clean:
	rm -f *.ali *.o *~ test_matrice_sure test_matrice_sure1 test_matrice_sure2 test_matrice_sure3
